#!/bin/bash

path=/home/$USER/.local/bin/calculon

cp calculon.py $path
chmod +x $path

echo "Installed at $path"

rc="/home/$USER/.bashrc"
if [[ $SHELL == *"zsh"* ]]; then
    rc="/home/$USER/.zshrc"
fi

echo "Do you want to add 'c' alias to $rc?"
echo "This will allow you to type: c 2 + 2 and get results"
read -p "Continue [y/n] " -r
echo
if [[ $REPLY =~ [Yy]$ ]]; then
    echo 'alias c=/home/$USER/.local/bin/calculon' >> $rc
    echo "Alias added!, enjoy!"
    echo "You might need to type: source $rc"
    echo "Or restart your terminal!"
else
    echo "No alias added, but you can still use"
    echo "calculon 2 + 2"
    echo "And add an alias later if you want!"
fi
